const FORM_TYPES = {
  OPEN_FORM_FOR_NEW_DATA: "OPEN_FORM_FOR_NEW_DATA",
  FORM_SELECTED_TO_EDIT: "FORM_SELECTED_TO_EDIT",
  FORM_TO_RENDER: "FORM_TO_RENDER",
  UPDATE_DATA_OF_FORM: "UPDATE_DATA_OF_FORM",
  ADD_TABLE_DATA: "ADD_TABLE_DATA",
  EDIT_TABLE_DATA: "EDIT_TABLE_DATA",
  DELETE_TABLE_DATA:"DELETE_TABLE_DATA",
  TEAM_PLAYER_DETAILS:"TEAM_PLAYER_DETAILS",
};
export { FORM_TYPES };
